=== fbognini/xml-sample/definition.dtd
<!DOCTYPE dati [
<!ELEMENT dati (persona+)>
<!ELEMENT persona (anagrafica,indirizzo,altridati)>
<!ELEMENT anagrafica (cognome,nome+)>
<!ELEMENT cognome (#PCDATA)>
<!ELEMENT nome (#PCDATA)>
<!ELEMENT indirizzo (toponimo,nomeindirizzo,civico)>
<!ELEMENT toponimo (#PCDATA)>
<!ELEMENT nomeindirizzo (#PCDATA)>
<!ELEMENT civico (numero,esponente)>
<!ELEMENT numero (#PCDATA)>
<!ELEMENT esponente (#PCDATA)>
<!ELEMENT altridati (grupposanguigno?,altezza,peso,data_nascita,sesso)>
<!ELEMENT grupposanguigno (#PCDATA)>
<!ELEMENT altezza (#PCDATA)>
<!ELEMENT peso (#PCDATA)>
<!ELEMENT data_nascita (#PCDATA)>
<!ELEMENT sesso (#PCDATA)>
]>

=== fbognini/xml-sample/dati.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/xsl" href="stile.xslt"?>
<!DOCTYPE dati SYSTEM "definition.dtd">

<dati>
	<persona>
		<anagrafica>
			<cognome>Alfonsini</cognome>
			<nome>Davide</nome>
			<nome>Luciano</nome>
			<nome>Giancarlo</nome>
		</anagrafica>
		<indirizzo>
			<toponimo>Via</toponimo>
			<nomeindirizzo>Garibaldi</nomeindirizzo>
			<civico>
				<numero>41</numero>
				<esponente>A</esponente>
			</civico>
		</indirizzo>
		<altridati>
			<grupposanguigno>B</grupposanguigno>
			<altezza>1.75</altezza>
			<peso>64</peso>
			<data_nascita>1964-08-31</data_nascita>
			<sesso>M</sesso>
		</altridati>		
	</persona>
	<persona>
		<anagrafica>
			<cognome>Bognini</cognome>
			<nome>Francesco</nome>
		</anagrafica>
		<indirizzo>
			<toponimo>Via</toponimo>
			<nomeindirizzo>Ca' Gandolfi</nomeindirizzo>
			<civico>
				<numero>3</numero>
				<esponente></esponente>
			</civico>
		</indirizzo>
		<altridati>
			<grupposanguigno>0</grupposanguigno>
			<altezza>1.83</altezza>
			<peso>70</peso>
			<data_nascita>2000-01-07</data_nascita>
			<sesso>M</sesso>
		</altridati>		
	</persona>
	<persona>
		<anagrafica>
			<cognome>Paguri</cognome>
			<nome>Susanna</nome>
		</anagrafica>
		<indirizzo>
			<toponimo>Piazza</toponimo>
			<nomeindirizzo>Matteotti</nomeindirizzo>
			<civico>
				<numero>12</numero>
				<esponente></esponente>
			</civico>
		</indirizzo>
		<altridati>
			<altezza>1.68</altezza>
			<peso>55</peso>
			<data_nascita>1975-02-28</data_nascita>
			<sesso>F</sesso>			
		</altridati>
	</persona>
	<persona>
		<anagrafica>
			<cognome>Scarpellini</cognome>
			<nome>Alice</nome>
			<nome>Maria</nome>
		</anagrafica>
		<indirizzo>
			<toponimo>Via</toponimo>
			<nomeindirizzo>da Urgnano</nomeindirizzo>
			<civico>
				<numero>66</numero>
				<esponente>6</esponente>				
			</civico>
		</indirizzo>
		<altridati>
			<grupposanguigno>AB</grupposanguigno>
			<altezza>1.45</altezza>
			<peso>50</peso>
			<data_nascita>1999-01-07</data_nascita>
			<sesso>F</sesso>
		</altridati>		
	</persona>
</dati>
